
export default {

    // Internal Events
    SHEMSYS_MOTION_STATE_UPDATED: 'SHEMSYS_MOTION_STATE_UPDATED',
    SHEMSYS_POWER_UPDATED: 'SHEMSYS_POWER_UPDATED',

    // Socket Client Events
    SHEMSYS_MOTION_STATE: 'SHEMSYS_MOTION_STATE',
    SHEMSYS_POWER: 'SHEMSYS_POWER',
    SHEMSYS_CURRENT_DATA_REQ: 'SHEMSYS_CURRENT_DATA_REQ',
    SHEMSYS_CURRENT_DATA: 'SHEMSYS_CURRENT_DATA'
};
